/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppLayoutRouteImport } from './routes/_app/layout'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppListUserRouteImport } from './routes/_app/list-user'
import { Route as AppListTechniciansRouteImport } from './routes/_app/list-technicians'
import { Route as AppListProducersRouteImport } from './routes/_app/list-producers'

const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppListUserRoute = AppListUserRouteImport.update({
  id: '/list-user',
  path: '/list-user',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppListTechniciansRoute = AppListTechniciansRouteImport.update({
  id: '/list-technicians',
  path: '/list-technicians',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppListProducersRoute = AppListProducersRouteImport.update({
  id: '/list-producers',
  path: '/list-producers',
  getParentRoute: () => AppLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/list-producers': typeof AppListProducersRoute
  '/list-technicians': typeof AppListTechniciansRoute
  '/list-user': typeof AppListUserRoute
  '/reports': typeof AppReportsRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/list-producers': typeof AppListProducersRoute
  '/list-technicians': typeof AppListTechniciansRoute
  '/list-user': typeof AppListUserRoute
  '/reports': typeof AppReportsRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppLayoutRouteWithChildren
  '/_app/list-producers': typeof AppListProducersRoute
  '/_app/list-technicians': typeof AppListTechniciansRoute
  '/_app/list-user': typeof AppListUserRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/list-producers'
    | '/list-technicians'
    | '/list-user'
    | '/reports'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/list-producers' | '/list-technicians' | '/list-user' | '/reports' | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/list-producers'
    | '/_app/list-technicians'
    | '/_app/list-user'
    | '/_app/reports'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/list-user': {
      id: '/_app/list-user'
      path: '/list-user'
      fullPath: '/list-user'
      preLoaderRoute: typeof AppListUserRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/list-technicians': {
      id: '/_app/list-technicians'
      path: '/list-technicians'
      fullPath: '/list-technicians'
      preLoaderRoute: typeof AppListTechniciansRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/list-producers': {
      id: '/_app/list-producers'
      path: '/list-producers'
      fullPath: '/list-producers'
      preLoaderRoute: typeof AppListProducersRouteImport
      parentRoute: typeof AppLayoutRoute
    }
  }
}

interface AppLayoutRouteChildren {
  AppListProducersRoute: typeof AppListProducersRoute
  AppListTechniciansRoute: typeof AppListTechniciansRoute
  AppListUserRoute: typeof AppListUserRoute
  AppReportsRoute: typeof AppReportsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppListProducersRoute: AppListProducersRoute,
  AppListTechniciansRoute: AppListTechniciansRoute,
  AppListUserRoute: AppListUserRoute,
  AppReportsRoute: AppReportsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppLayoutRoute: AppLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
